
* PIC simulation of V-A characteristic of a probe

This program was created for the final assignment for the PMPL (computer
modeling of plasma) course. It is a 2D3V PIC code with an optional Boris
integrator scheme for a perpendicular, homogeneous magnetic field. 

The code simulated a square probe in the center of a square grid and measures
the incident current on the probe for a given applied voltage. This V-A
characteristic is the fitted with an analytic curve a for Langmuir probes.

It is likely buggy and unreliable. Nevertheless, it gives a reasonable curve
shape for the V-A characteristic of a probe.

** Running the simulation
1) check that dependencies in [[requirements.txt]] are satisfied (using e.g. ~pip install -r .~)
2) run the script ~./run_simulation.py~ with default parameters or tune the
   parameters described by the ~--help~ option
3) the script will show a graph of the fitted V-A characteristic of a probe in the center

** Implementation details
The code is written using NumPy ndarray containers for data access and storage.
for-cycle heavy pieces of code are optimized using the Numba JIT compiler.

It uses CIC weighting and LU factorization for solving the Poisson equation.
